name: Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths-ignore:
      - '.github/workflows/release.yml'
      - '.github/workflows/pr_checks.yml'

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    name: Pre-commit
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.1.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/dontshavetheyak/terraform-template-module-devcontainer
          runCmd: pre-commit run -a

  test:
    needs: pre_commit
    runs-on: ubuntu-latest
    name: Terraform Latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.1.0

      - name: Setup latest Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.18

      - name: Test
        working-directory: tests
        run: go test

  multi:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform-version: ['0.12.31', '0.13.7', '0.14.11', '0.15.5']
    name: Terraform ${{ matrix.terraform-version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.1.0

      - name: Setup Terraform ${{ matrix.terraform-version }}
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform-version }}
          terraform_wrapper: false

      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.18

      - name: Test
        working-directory: tests
        run: go test
